package services

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"
)

// LocalAuthProvider provides local authentication against the database
// This is used for local development without AWS Cognito
type LocalAuthProvider struct {
	db *pgxpool.Pool
}

// NewLocalAuthProvider creates a new local auth provider
func NewLocalAuthProvider(db *pgxpool.Pool) *LocalAuthProvider {
	return &LocalAuthProvider{db: db}
}

// AuthenticateUser authenticates a user with email and password against the database
func (p *LocalAuthProvider) AuthenticateUser(ctx context.Context, email, password string) (*AuthResult, error) {
	var userID uuid.UUID
	var passwordHash string

	query := `SELECT id, password_hash FROM users WHERE email = $1 AND is_active = true`
	err := p.db.QueryRow(ctx, query, email).Scan(&userID, &passwordHash)
	if err != nil {
		return nil, fmt.Errorf("user not found or inactive")
	}

	// Verify password
	if err := bcrypt.CompareHashAndPassword([]byte(passwordHash), []byte(password)); err != nil {
		return nil, fmt.Errorf("invalid password")
	}

	// Return a mock auth result (access token will be generated by AuthService)
	return &AuthResult{
		AccessToken:  userID.String(), // Will be replaced by actual JWT
		RefreshToken: uuid.New().String(),
		ExpiresIn:    3600,
	}, nil
}

// RefreshToken returns a new auth result for token refresh
func (p *LocalAuthProvider) RefreshToken(ctx context.Context, refreshToken string) (*AuthResult, error) {
	// In local mode, just return a new token
	return &AuthResult{
		AccessToken:  uuid.New().String(),
		RefreshToken: refreshToken,
		ExpiresIn:    3600,
	}, nil
}

// GetUser retrieves user info from the database
func (p *LocalAuthProvider) GetUser(ctx context.Context, userID string) (*CognitoUser, error) {
	id, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	var user CognitoUser
	query := `SELECT id, email, name FROM users WHERE id = $1`
	err = p.db.QueryRow(ctx, query, id).Scan(&user.Sub, &user.Email, &user.Name)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	user.Username = user.Email
	user.EmailVerified = true

	return &user, nil
}

// GlobalSignOut is a no-op for local auth
func (p *LocalAuthProvider) GlobalSignOut(ctx context.Context, accessToken string) error {
	return nil
}

// RevokeToken is a no-op for local auth
func (p *LocalAuthProvider) RevokeToken(ctx context.Context, refreshToken string) error {
	return nil
}
